name: CD Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Unit-Tests-Application:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt-get install nodejs -y
      - run: sudo apt install npm
      - run: nodejs -v
      - run: npm -v
      - run: npm install -g @angular/cli
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm install
      - run: npm ci
      - run: npm run test:prod
  Deploy:
    runs-on: ubuntu-latest
    needs: Unit-Tests-Application
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
